### PR TITLE
Better, Cleaner and updated translation for pt_BR

### PR DESCRIPTION
**Pull request by InterPlay02**
Well... That's it. I've made a better, cleaner and updated version of the translation file, for pt_BR language.
If someone still working on this mod, for 1.7.10... I hope you can use it.
And, if you still using the same items and blocks in newer versions of the mod, you can use this translation as well.

### CODE REVIEW

**Review by bziemons — CHANGES_REQUESTED** [review]
You may not remove the copyright notice (first five lines), but instead add yourself to it.

**Comment by InterPlay02** [comment]
Changes have been done. @theZorro266

**Review by dblsaiko — CHANGES_REQUESTED** [review]
Items/blocks are no longer named like 'item.PipeItemsBasicTransport'. See [en_us.lang](https://github.com/RS485/LogisticsPipes/blob/dev-mc1122/resources/assets/logisticspipes/lang/en_us.lang)

**Comment by InterPlay02** [comment]
You say that because you are looking at the 1.12.2 version of the mod.
This translation is not for 1.12.2, man.... @2xsaiko 
This is for 1.7.10... Haven't you read my first comment explaining?

**Review by dblsaiko — APPROVED** [review]
Right, my bad.

**Review by bziemons — APPROVED** [review]

**Pull request merged**
